spring:
  data:
    mongodb:
      host: '192.168.0.106'
      port: 27017
      database: 'koochita'

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8091

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: 'DEBUG'
